---
title: "Género y TIC"
description: |
  Información sobre el programa "Género y TIC" de Ciudadanía Digital.
  La propuesta busca dar a conocer mujeres que han incursionado en el mundo de las TIC de forma destacada (exitosa/novedosa) para difundir las diferentes posibilidades de estudio y trabajo en tecnología, e incentivar a niñas, niños y jóvenes a incursionar en el área. Fue creado en 2018.

---

```{r nice-figcd1, fig.cap = "Ciudadanía Digital", out.width='80%', fig.asp=.75, fig.align='center', echo=FALSE}
#install.packages("DiagrammeR")
#font-family:Consolas
DiagrammeR::grViz("digraph {
# dot, circo, twopi, neato
  #graph [layout = dot, rankdir = ]
  graph [layout = dot, rankdir = TB, overlap = False]
  #shape = rpromoter, folder, cds
  node [shape = plaintext, fontname=Verdana, fontcolor=DarkGrey, margin =0.25]    
  
  n0 [label = 'Ciudadanía Digital']
  
  n1 [label = 'Género y TIC']

  # edge definitions with the node IDs
  edge [color=grey]
  
   n0 -> n1

   
  
}",)

```




## Piloto Género y TIC: Informe 2019- 2020


### Introducción

El presente informe tiene como objetivo dar cuenta del desarrollo del piloto sobre Género y TIC en educación, que abarcó el desarrollo del Ciclo de Videoconferencias Género y TIC, así como actividades para docentes sobre la integración de perspectiva de género en el trabajo con tecnología en el aula, en el período 2019 - 2020. 
Equipo de trabajo: Nerey Long, Lucía Fernández, Natalia Moraes, Milena Delgado, Noelia Vizuete, Lucía Menyou, Camila Bouyssounade, Patricia Goñez, Pablo Pagés, Patricia Brown. 

Desde el programa Aprender Todos se promueve la generación de espacios y estrategias que permitan una mayor apropiación de los recursos digitales y de Plan Ceibal disponibles, para el aprendizaje y la inclusión social, a través de estrategias participativas que promuevan su uso significativo.  En ese recorrido mediado por la intervención de tecnología, se promueve la participación igualitaria de niños, niñas y jóvenes para el ejercicio de una ciudadanía digital plena.  así como en pos de favorecer la reducción de la brecha de género en áreas STEM. El programa asume el desafío de fortalecer las intervenciones de manera que ofrezcan espacios de participación para niñas, niños y jóvenes y apoye a los docentes en el desarrollo de estas estrategias y proyectos. 

En esta línea, Plan Ceibal integra la Mesa Interinstitucional de Mujeres en Ciencia, Tecnología e Innovación, que forma parte del Proyecto Internacional SAGA-UNESCO. Esta iniciativa busca contribuir a la mejora de las condiciones y oportunidades para la participación y acceso de las mujeres en los distintos ciclos educativos en campos asociados a dichas áreas, en todos los niveles de los sistemas nacionales de investigación, y en las estructuras productivas e institucionales que permitan deconstruir roles y estereotipos de género que parecen operar “naturalmente”. 



### 2) Desarrollo
Descripción general de la propuesta

La propuesta de Ciclo de videoconferencias consiste en la realización de entrevistas e intercambios con mujeres destacadas en el área de las TIC (preferentemente uruguayas), con la participación de grupos de estudiantes y docentes a través de videoconferencia. 

En cada encuentro participa una mujer del área de las TIC que comparte su experiencia y trayecto en la temática, con los grupos de estudiantes, quienes tienen la oportunidad de realizar preguntas.
La propuesta implica la preparación del grupo de estudiantes para participar en el intercambio. Estas actividades previas poseen soporte desde la plataforma Crea, mediante foros de discusión, materiales de consulta y orientación para el desarrollo de actividades. 

Se realiza de forma virtual, contemplando actividades desde plataforma Crea así como la posibilidad de conexión a las videoconferencias desde los hogares. 

El ciclo está destinado a alumnos de 5to. y 6to. educación primaria, y 1ro. y 2do. educación media, con docente a cargo.
El lanzamiento de la propuesta se realizó cada año el cuarto jueves del mes de abril, fecha en que se celebra el Día Internacional de las Niñas en las TIC y se llevan a cabo diferentes actividades a nivel mundial, para promover la participación de niñas y jóvenes en estas áreas. 

### Objetivos del programa

Dar a conocer mujeres que han incursionado en el mundo de las TIC de forma destacada (exitosa/novedosa) para difundir las diferentes posibilidades de estudio y trabajo en tecnología, e incentivar a niñas, niños y jóvenes a incursionar en el área. 

Involucrar a estudiantes y docentes en actividades de investigación sobre la participación de mujeres en áreas de tecnología, los desafíos que afrontan y los beneficios de una participación equitativa. 

Generar espacios de reflexión a partir del intercambio a nivel del grupo de estudiantes y en la instancia de intercambio por videoconferencia, con otros grupos de estudiantes y la persona invitada al encuentro. 

Promover el desarrollo de actividades en CREA, así como el aprovechamiento de otros  recursos ofrecidos por Plan Ceibal. 

###  Actividades realizadas

**a) Ciclo de videoconferencias**

#### Ejecución 2019 - Abril/Noviembre

Se recibieron 63 postulaciones, de las cuales se confirmaron 39 participaciones que involucraron a 35 centros educativos de 15 departamentos. Estimamos un promedio de 6,5 centros participando por encuentro. Se registraron 1050 estudiantes participando.

Se realizaron 6 intercambios por videoconferencia, con apoyo de actividades desde plataforma Crea. 

Las invitadas fueron:
Sofía Donner, Intérprete visual, ilustradora, y diseñadora.

Mónica Marín, Doctora en Bioquímica, Investigadora y Decana de Facultad de Ciencias, UdelaR.

Alicia Carriquiri, Ingeniera Agrónoma, Doctora en Estadística y Genética Animal, Directora del Centro de Estadística y 
Aplicaciones en Evidencia Forence en el estado de Iowa en Estados Unidos.

Sofía Battegazzore, Emprendedora y Productora de Videojuegos.

Agustina Sartori,Ingeniera telemática y Co-fundadora y Gerente de GlamST, una plataforma uruguaya de maquillaje virtual.

Florencia Grattarola. Bióloga e Investigadora. Estudiante de Doctorado en el área de Ecología y Evolución, en la Universidad de Lincoln, Reino Unido.

#### Ejecución 2020 - Agosto/Octubre

Se recibieron 34 postulaciones, de las cuales se confirmaron 23 participaciones que involucraron a 21 centros educativos de 10 departamentos. Estimamos un promedio de 8 centros participando por encuentro. Se registraron 312 estudiantes y 30 docentes participando. 

Se realizaron 3 intercambios por videoconferencia, cada uno con sus actividades previas y posteriores. 
Las invitadas fueron:

Paula Enciso, Bioquímica, docente e investigadora en Facultad de Ciencias UdelaR y docente en Universidad Tecnológica

Virginia Robano, Economista, se desempeña en áreas de ciencia de datos e implementación de políticas de desarrollo económico y mercado laboral. 

Gime “Alaska”, generadora de contenido para youtube, conductora de C+ Maratón Transmedia. 

El equipo Ceibal coordinó la participación de las entrevistadas así como la convocatoria y confirmación de los centros educativos, liderando el desarrollo de los intercambios. Luego se acompañó la participación de los mismos y posteriormente se atendieron consultas y evaluación.


b) Actividades formativas dirigidas a docentes


En el marco de la Escuela de verano 2020 se realizó el taller “Género y TIC en educación: espacio de reflexión y construcción”. Dirigido a docentes interesados en la temática, contó con 35 participantes. 
Se realizó el Seminario virtual "Educación, Género y TIC: reflexiones, aprendizajes y orientaciones para la acción", con la participación de Anabella Benedetti, Investigadora de la Cátedra Regional Unesco Mujer, Ciencia y Tecnología en América Latina (Flacso, Argentina). Este seminario se realizó el día 23 de abril de 2020, para celebrar el día internacional de las niñas en las TIC y ofició como lanzamiento del Ciclo de videoconferencias Género y TIC. El seminario se transmitió en vivo a través del canal de Youtube de Plan Ceibal. Contó con 80 participantes en vivo y más de 1500 visualizaciones posteriores. 
Realización del webinar “Género y TIC en educación” - Belén Fernández - 1er encuentro. Dirigido a estudiantes de formación docente y docentes en general, contó con la participación en vivo de 250 personas y 170 visualizaciones posteriores. Fue realizado a través de vivo de Instagram de Plan Ceibal. 
Realización de webinar “Género y TIC en educación” - Elisa Cristi - 2do encuentro. Dirigido a estudiantes de formación docente y docentes en general, contó con la participación en vivo de 150 personas y 156 visualizaciones posteriores. Fue realizado a través de vivo de Instagram de Plan Ceibal. 

d) Avance en relación a las metas

Meta
Dato a Diciembre 2020
Grado de cumplimiento
cantidad encuentros por vc
9
cumplido
cantidad de estudiantes participantes
1362
cumplido


### Balance y perspectivas 

Dificultades

El contexto de pandemia y las decisiones de ajuste de la propuesta priorizaron la modalidad de trabajo, entendiendo que el trabajo de todo el grupo de clase con la orientación del docente a cargo es una fortaleza de la propuesta. Esto implicó un ajuste en el cronograma, en cuanto a fechas y cantidad de encuentros, que afectó la cantidad de estudiantes y docentes involucrados en relación a ediciones anteriores. Destacamos que aumentó el promedio de grupos participando por encuentro. 
Ha sido un desafío el seguimiento posterior a la VC para conocer la amplificación que puede tener la propuesta luego del intercambio. 

Oportunidades

A partir de la situación de emergencia sanitaria y las consecuencias en el ámbito educativo, se reformuló el calendario de trabajo el cual se concentró entre los meses de agosto y octubre, y se redujo la cantidad de intercambios a la mitad. Esto buscó mantener la modalidad de trabajo en la cual el grupo de estudiantes participa de forma conjunta en la videoconferencia, entendiendo que favorece el dinamismo y la participación activa de los grupos durante el intercambio. 
Se aumentó el tiempo de trabajo previo al intercambio en la plataforma, para favorecer la participación de los estudiantes, considerando la alternancia en la asistencia a los centros y la modalidad de trabajo combinada virtual/presencial.
Satisfacción de los centros participantes con la propuesta.
Los docentes valoraron la propuesta, destacando la disposición y calidad de los materiales disponibles en plataforma en Crea así como la calidad del intercambio y la oportunidad que significó para los estudiantes intercambiar directamente con las invitadas en cada encuentro. 
Alto impacto y bajo costo de la propuesta.
Se evalúa positivamente en términos de organización de los encuentros, la inscripción temprana. La confirmación de participantes se vio agilizada. 
Los docentes valoraron positivamente el tiempo disponible para preparar la participación en el intercambio, a partir de los materiales en plataforma Crea. 
Destacamos que se logró la participación de centros que no contaban con equipo de videoconferencia, a partir de la articulación del sistema con plataforma webex. 
Se destaca positivamente la integración del equipo que ha liderado el desarrollo de las propuestas, destacando el trabajo colaborativo, el aporte de diversas miradas y disciplinas. 



#### Desafíos 2021

En relación al Ciclo de videoconferencias:

Promover en mayor medida que la propuesta se encuentre presente en los proyectos desarrollados por los centros educativos.

Potenciar la difusión de la propuesta en territorio. 

En cuanto al perfil de las entrevistadas, y a partir de resultados 2019 y 2020, mantener la atención a características que puedan representar mayor cercanía con los estudiantes. 
Mantener enlace con sistema webex para favorecer la participación de centros que no cuentan con equipo de videoconferencia, así como ante contingencias por pandemia, estudiantes que deban permanecer en sus hogares o grupos puedan participar. 
Integrar perspectiva de género en tecnología en el diseño de intervención y materiales de apoyo para los componentes Aprender Todos (Educación Media, Formación en Educación y Educación Primaria - Programa de Maestros Comunitarios). 
Articulación de la temática género y TIC con línea Ciudadanía Digital.
Formación al equipo Referentes de Proyecto sobre la perspectiva de género en tecnología. 
Desarrollo de una propuesta formativa para docentes sobre perspectiva de género en enseñanza STEAM. 
Mantener un equipo de trabajo que contribuya en la profundización del abordaje de la temática en línea con el desarrollo de la Ciudadanía Digital. 

## Conclusiones 

El desarrollo del piloto fue evaluado positivamente a partir del alcance de las metas y los resultados obtenidos. El contexto de pandemia implicó ajustes en el cronograma y ajustes  técnicos, así como revisión de estrategias de comunicación, que favorecieron el desarrollo de la propuesta y redundaron en aprendizajes para un mejor aprovechamiento de la propuesta. 
La posibilidad de incluir la perspectiva de género en tecnología en el diseño de actividades para los componentes de  Aprender Todos (Educación Media, CFE, PMC), aporta a la formación de  los docentes así como fortalece el abordaje de la temática en proyectos de los centros educativos involucrados. 
A nivel del equipo de Referentes de Proyecto, las acciones de sensibilización sobre la integración de la perspectiva de género en el trabajo con tecnología en educación, aportan herramientas para la intervención en territorio. 
Concluimos que la integración de esta línea de trabajo tiene validez en tanto fortalece la integración de la perspectiva de género en el desarrollo de ciudadanía digital y la intervención a nivel de componentes. A la vez que enriquece la propuesta de formación desde el programa.




